Add the Template file
kevinaangstadt/CS340-Summer21-Notes pull request #35
Opened 2021-07-02 00:14 UTC by superslalomracer

This is for the purpose of internal use to help with formatting and editing of each other's code. 

Add markdown file to be used as a template for review and all
future notes. Open for edits until a date specified in the
related issue. After the file is final, all notes can be
edited to conform.

Template file describes convention for using example code as
both python and bash code, details an organization based on
main topics and a general commands at the end.

2021-07-04 18:54 UTC, kevinaangstadt requested changes
Please address the comments in this review.

2021-07-04 18:54 UTC, kevinaangstadt commented on Lecture_template.md
> +python example code(foo)
GitHub md has a way of specifying the language for the block of code (e.g., ```python) 

Please update accordingly

2021-07-04 18:54 UTC, kevinaangstadt commented on Lecture_template.md
> +```
Same as Line 22, you can specify the language of this code block

2021-07-04 18:54 UTC, kevinaangstadt commented on Lecture_template.md
> +## **Overview**
Issue #33 discussion suggests removing this section

2021-07-04 19:56 UTC, superslalomracer commented
All requested changes have been made. New PR will be opened shortly.

2021-07-05 19:19 UTC, kevinaangstadt approved these changes

2021-07-05 19:19 UTC, merged